@startuml
'https://plantuml.com/class-diagram

class Thread
class threading
class queue
class Event
class cv2
class numpy
class time
class controller

Thread <|-- batchqueue
threading <|-- Thread
threading <-- batchqueue
queue --* batchqueue
threading <|-- Event
Event --o batchqueue
iprocess <|-- depthrecognition
cv2 <-- depthrecognition
numpy <-- depthrecognition
idatagather <|-- cameradepthgather
time <-- cameradepthgather
controller <-- cameradepthgather
ibatch <|-- batchqueue
ibatch <-- datahandler
idatagather <-- datahandler
Event <-- datahandler
Thread <|-- datahandler
idatagather <|-- camerarecognitiongather
iprocess <|-- objectrecognition
idatagather <|-- imugather
iprocess <|-- imuprocess
idatagather <|-- textgather
iprocess <|-- textprocess
ibatch ..o sensoradmin
ibatch ..o decisionadmin
model --* decisionadmin
model_preprocess --o decisionadmin
iprocess <-- datahandler
interface iprocess{
    process_data(data)
}

class depthrecognition{
    +NUM_DISPARITIES
    +BLOCKSIZE
    +process_data(data)
    +pair_func(data, func)
    +grayscale(image)
    +rotate90(image)
    +rotate90counter(image)
    +create_stereoBM()
    +depth(image1, image2)
    +mix(image1, image2)
}

interface idatagather{
    +__init__(device)
    +get_data()
}

class cameradepthgather{
    -__camera
    +__init__(device)
    +get_data()
    -__get_image()
}

interface ibatch{
    +interval()
    +interval(value)
    +dequeue()
    +enqueue(item)
}

class batchqueue{
    -__queue
    -__interval
    -__stop
    +__init__(size=2, interval = 0.1)
    +run()
    +stop()
    +interval()
    +interval(value)
    +dequeue()
    +enqueue(item)
    +qsize()
}

class datahandler{
    -__batch
    -__process
    -__data_gatherer
    -__stop
    +__init__(batch, process, data_gatherer, )
    +get_data()
    +pass_data(data)
    +process_data(data)
    +stop()
    +run()
}

class camerarecognitiongather{
    -__camera
    +__init__(device)
    +get_data()
    -__get_image()
    }

class objectrecognition{
    +process_data()
    }

class imugather{
    -__inertial_unit
    +__init__(device)
    +get_data()
}

class imuprocess{
    +process_data()
}

class textgather{
    -__textgenerator
    +__init__(device)
    +get_data()
}

class textprocess{
    +process_data()
}

class sensoradmin{
    +run()
    +create_batch()
    +push_data()
}

class decisionadmin{
    -__preprocess
    -__model
    -__in_batch
    -__out_batch
    +decide()
    +get_data()
    +push_data()
}

class model{
    -cosas
    +predict()
}

class model_preprocess{
    +process_data()
}

class actuatoradmin{
    -__list_actuators
    +send
}
iprocess <|--model_preprocess
iactuatorcontroller --o actuatoradmin
iactuatorcontroller <|-- motorcontroller
interface iactuatorcontroller{
    +set_order()
}

class motorcontroller{
    +order()
}

enum sensors{
    +IMU
    +DEPTH
    +RECOGNITION
    +TEXT
}
enum actuators{
    +RARE_LEFT_MOTOR
    +RARE_RIGHT_MOTOR
    +FRONT_LEFT_MOTOR
    +FRONT_RIGHT_MOTOR
}
@enduml